/*
** PERSONNAL PROJECT, 2024
** Pokebraindle
** File description:
** Auto-generated file that lists all available assets
** Do not modify by hand.
*/

#ifndef CT_HPP_
    #define CT_HPP_
#include <array>
#include <string>
#include <limits>
#include <cstdint>

    enum CtId {
        CT01 = 0,
        CT02 = 1,
        CT03 = 2,
        CT04 = 3,
        CT05 = 4,
        CT06 = 5,
        CT07 = 6,
        CT08 = 7,
        CT09 = 8,
        CT10 = 9,
        CT11 = 10,
        CT12 = 11,
        CT13 = 12,
        CT14 = 13,
        CT15 = 14,
        CT16 = 15,
        CT17 = 16,
        CT18 = 17,
        CT19 = 18,
        CT20 = 19,
        CT21 = 20,
        CT22 = 21,
        CT23 = 22,
        CT24 = 23,
        CT25 = 24,
        CT26 = 25,
        CT27 = 26,
        CT28 = 27,
        CT29 = 28,
        CT30 = 29,
        CT31 = 30,
        CT32 = 31,
        CT33 = 32,
        CT34 = 33,
        CT35 = 34,
        CT36 = 35,
        CT37 = 36,
        CT38 = 37,
        CT39 = 38,
        CT40 = 39,
        CT41 = 40,
        CT42 = 41,
        CT43 = 42,
        CT44 = 43,
        CT45 = 44,
        CT46 = 45,
        CT47 = 46,
        CT48 = 47,
        CT49 = 48,
        CT50 = 49,

        CT_COUNT,
    };

    const std::array<std::string, CT_COUNT> CtNames = {
        "Ultimapoing",
        "Coupe-Vent",
        "Danse-Lames",
        "Cyclone",
        "Ultimawashi",
        "Toxik",
        "Empal'Korne",
        "Plaquage",
        "Bélier",
        "Damoclès",
        "Bulles d'O",
        "Pistolet à O",
        "Laser Glace",
        "Blizzard",
        "Ultralaser",
        "Jackpot",
        "Sacrifice",
        "Riposte",
        "Frappe Atlas",
        "Frénésie",
        "Méga-Sangsue",
        "Lance-Soleil",
        "Draco-Rage",
        "Tonnerre",
        "Fatal-Foudre",
        "Séisme",
        "Abîme",
        "Tunnel",
        "Psyko",
        "Téléport",
        "Copie",
        "Reflet",
        "Protection",
        "Patience",
        "Métronome",
        "Destruction",
        "Bomb'Oeuf",
        "Déflagration",
        "Météores",
        "Coud'Krâne",
        "E-Coque",
        "Dévorêve",
        "Piqué",
        "Repos",
        "Cage-Eclair",
        "Vague Psy",
        "Explosion",
        "Eboulement",
        "Triplattaque",
        "Clonage",
    };

    const std::array<std::string, CT_COUNT> CtTypes = {
        "Normal",
        "Normal",
        "Normal",
        "Normal",
        "Normal",
        "Poison",
        "Normal",
        "Normal",
        "Normal",
        "Normal",
        "Eau",
        "Eau",
        "Glace",
        "Glace",
        "Normal",
        "Normal",
        "Combat",
        "Combat",
        "Combat",
        "Normal",
        "Plante",
        "Plante",
        "Poison",
        "Electrique",
        "Electrique",
        "Sol",
        "Sol",
        "Sol",
        "Psy",
        "Psy",
        "Normal",
        "Normal",
        "Psy",
        "Normal",
        "Normal",
        "Normal",
        "Normal",
        "Feu",
        "Normal",
        "Normal",
        "Normal",
        "Psy",
        "Vol",
        "Psy",
        "Electrique",
        "Psy",
        "Normal",
        "Roche",
        "Normal",
        "Normal",
    };

    const std::array<std::int32_t, CT_COUNT> CtPower = {
        80,
        80,
        -1,
        -1,
        -1,
        -1,
        -1,
        85,
        90,
        100,
        65,
        40,
        95,
        120,
        150,
        40,
        80,
        -1,
        -1,
        20,
        40,
        120,
        -1,
        95,
        95,
        100,
        -1,
        100,
        90,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        130,
        100,
        120,
        60,
        100,
        -1,
        100,
        140,
        -1,
        -1,
        -1,
        170,
        75,
        80,
        -1,
    };

    const std::array<std::int32_t, CT_COUNT> CtAccuracy = {
        85,
        100,
        -1,
        100,
        100,
        85,
        30,
        100,
        85,
        100,
        100,
        100,
        100,
        90,
        90,
        100,
        80,
        100,
        100,
        100,
        100,
        100,
        100,
        100,
        100,
        100,
        30,
        100,
        100,
        -1,
        -1,
        -1,
        -1,
        -1,
        -1,
        100,
        75,
        85,
        -1,
        100,
        -1,
        100,
        90,
        -1,
        100,
        80,
        100,
        90,
        100,
        -1,
    };

#endif /* !CT_HPP_ */
